// frontend/src/pages/Register.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../services/api';

const Register = () => {
  const [formData, setFormData] = useState({
    username: '',
    email: '',
    password: '',
    phone: '',
    business_name: '',
    business_type: 'retail'
  });
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const handleRegister = async (e) => {
    e.preventDefault();
    try {
      const { data } = await api.post('/auth/register', formData);
      localStorage.setItem('accessToken', data.accessToken);
      localStorage.setItem('user', JSON.stringify(data.user));
      navigate('/');
    } catch (err) {
      setError(err.response?.data?.message || 'Registration failed');
    }
  };

  return (
    <div className="flex flex-col items-center justify-center h-screen bg-gray-50">
      <form onSubmit={handleRegister} className="bg-white p-6 rounded-lg shadow-md w-96">
        <h2 className="text-2xl font-bold mb-6 text-center text-blue-600">Join BestLady</h2>
        {error && <p className="text-red-500 mb-4">{error}</p>}
        <input 
          type="text" 
          placeholder="Username" 
          onChange={(e) => setFormData({...formData, username: e.target.value})}
          className="border p-2 mb-4 w-full rounded focus:outline-blue-500"
          required
        />
        <input 
          type="email" 
          placeholder="Email" 
          onChange={(e) => setFormData({...formData, email: e.target.value})}
          className="border p-2 mb-4 w-full rounded focus:outline-blue-500"
          required
        />
        <input 
          type="password" 
          placeholder="Password" 
          onChange={(e) => setFormData({...formData, password: e.target.value})}
          className="border p-2 mb-4 w-full rounded focus:outline-blue-500"
          required
        />
        <input 
          type="text" 
          placeholder="Phone Number" 
          onChange={(e) => setFormData({...formData, phone: e.target.value})}
          className="border p-2 mb-4 w-full rounded focus:outline-blue-500"
          required
        />
        <input 
          type="text" 
          placeholder="Business Name" 
          onChange={(e) => setFormData({...formData, business_name: e.target.value})}
          className="border p-2 mb-4 w-full rounded focus:outline-blue-500"
          required
        />
        <select 
          value={formData.business_type}
          onChange={(e) => setFormData({...formData, business_type: e.target.value})}
          className="border p-2 mb-6 w-full rounded focus:outline-blue-500 bg-white"
        >
          <option value="retail">Retail</option>
          <option value="mall">Mall</option>
          <option value="large_supermarket">Large Supermarket</option>
          <option value="chain_store">Chain Store</option>
        </select>
        <button type="submit" className="bg-blue-600 text-white p-2 w-full rounded hover:bg-blue-700 transition">
          Create Account
        </button>
      </form>
    </div>
  );
};

export default Register;

// client_side/frontend/src/views/Register.vue
<template>
  <div class="max-w-md mx-auto py-12">
    <div class="bg-white p-8 rounded-lg shadow">
      <h2 class="text-2xl font-bold text-center mb-6">Create Account</h2>
      <form @submit.prevent="handleRegister">
        <div class="mb-4">
          <Input v-model="form.username" label="Username" placeholder="Enter username" required />
        </div>
        <div class="mb-4">
          <Input v-model="form.email" type="email" label="Email" placeholder="Enter email" required />
        </div>
        <div class="mb-4">
          <Input v-model="form.password" type="password" label="Password" placeholder="Enter password" required />
        </div>
        <div class="mb-4">
          <Input v-model="form.phone" label="Phone Number" placeholder="2547XXXXXXXX" required />
        </div>
        <div class="mb-4">
          <Input v-model="form.business_name" label="Business Name" placeholder="Enter business name" required />
        </div>
        <div class="mb-6">
          <label class="block text-sm font-medium text-gray-700 mb-1">Business Type</label>
          <select v-model="form.business_type" class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500" required>
            <option value="">Select Business Type</option>
            <option value="salon">Salon (Individual)</option>
            <option value="mini_supermarket">Mini Supermarket</option>
            <option value="beauty_shop">Beauty Shop</option>
            <option value="freelance">Freelance Stylist</option>
            <option value="mall">Mall</option>
            <option value="large_supermarket">Large Supermarket</option>
            <option value="chain_store">Chain Store</option>
            <option value="distributor">Distributor</option>
            <option value="exporter">Exporter</option>
            <option value="institution">Institution</option>
          </select>
        </div>
        <button type="submit" :disabled="loading" class="btn-primary w-full">
          {{ loading ? 'Creating Account...' : 'Register' }}
        </button>
      </form>
      <p class="text-center mt-4">
        Already have an account? <router-link to="/login" class="text-primary-600 hover:underline">Login</router-link>
      </p>
    </div>
  </div>
</template>

<script setup>
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import api from '@/services/api'
import { useAuthStore } from '@/stores/auth'
import { useToast } from 'vue-toast-notification'
import Input from '@/components/common/Input.vue'

const router = useRouter()
const auth = useAuthStore()
const toast = useToast()
const loading = ref(false)

const form = reactive({
  username: '',
  email: '',
  password: '',
  phone: '',
  business_name: '',
  business_type: '',
  role: 'user'
})

const handleRegister = async () => {
  loading.value = true
  try {
    const { data } = await api.post('/auth/register', form)
    auth.setAuth(data)
    toast.success('Registration successful! Welcome to BestLady!')
    router.push('/')
  } catch (error) {
    toast.error(error.response?.data?.message || 'Registration failed')
  } finally {
    loading.value = false
  }
}
</script>
